### ISSUE TITLE
Вопрос по поводу навигации

### ISSUE THREAD

**Issue by AmV1to** [2gis/mobile-sdk-android-demo#203]
Запускаю демо проект и получаю вот такую ошибку, подскажите пожалуйста, что может быть не так
```
FATAL EXCEPTION: main
      Process: com.deck_chair, PID: 29910
      ru.dgis.sdk.NativeException: Navigation is not supported by the key.
       at ru.dgis.sdk.navigation.NavigationManager.start(Native Method)
       at ru.dgis.sdk.demo.vm.NavigationViewModel.startNavigation(NavigationViewModel.kt:263)
       at ru.dgis.sdk.demo.NavigationActivity.onCreate$lambda$5$lambda$4(NavigationActivity.kt:103)
       at ru.dgis.sdk.demo.NavigationActivity.$r8$lambda$9j30ieX_4-FKVq5JvwMBwUZmqYg(Unknown Source:0)
       at ru.dgis.sdk.demo.NavigationActivity$$ExternalSyntheticLambda3.onClick(Unknown Source:2)
       at android.view.View.performClick(View.java:7570)
       at android.view.View.performClickInternal(View.java:7540)
       at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
       at android.view.View$PerformClick.run(View.java:29710)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8370)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by lagner** [comment]
Привет. Вся суть тут
`Navigation is not supported by the key`  
Чтобы навигация работала, нужно получить ключ в котором такая возможность активирована. Можно обратиться к вашему менеджеру за подробностями
